image: mwallasch/docker-ruby-node
services: 
  - library/postgres:9.4.4
  - library/elasticsearch:1.6.2
script:
  - mkdir -p /tmp/bundle
  - bundle install -j8 --path /tmp/bundle
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:schema:load rake