# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3154eef66be89b6ef4c7bbc3c0da6f43ce440ec5881a3e100fb0afcbfd1791713707ed71fd4c4c1db450c38cabd3b9bff194cd9ee709c084f866c2fd822b0e46

test:
  secret_key_base: ef551eb22e04a35c500c67c61f61813c5abb6ae5403ab6e3150604caa7203400c68aa4aa5ac896a18ccac0b1f1548f33c50b75fe5d163376e0257c19ae419a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
